# Generated by Django 2.2 on 2019-05-07 18:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import employers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(max_length=64, null=True)),
                ('email', models.CharField(max_length=128)),
                ('salary', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('date_hired', models.DateField(null=True)),
                ('notes', models.CharField(max_length=128, null=True)),
                ('reference', models.IntegerField(choices=[(0, 'Facebook'), (1, '4programmers'), (2, 'Staff'), (3, 'Applicant')])),
            ],
        ),
        migrations.CreateModel(
            name='DevelopersTechnologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employers.Developers')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('developer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employers.Developers')),
                ('street', models.CharField(max_length=128)),
                ('postal_code', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('city', models.CharField(max_length=128)),
                ('phone_number', models.IntegerField(null=True)),
                ('regon', models.IntegerField(null=True)),
                ('pesel', models.IntegerField(null=True)),
                ('nip', models.IntegerField(null=True)),
                ('company_name', models.CharField(max_length=128, null=True)),
                ('account_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_name', models.CharField(max_length=128)),
                ('developers', models.ManyToManyField(through='employers.DevelopersTechnologies', to='employers.Developers')),
            ],
        ),
        migrations.AddField(
            model_name='developerstechnologies',
            name='technology_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employers.Technologies'),
        ),
        migrations.CreateModel(
            name='DevelopersContracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.FileField(blank=True, null=True, upload_to=employers.models.contract_path)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employers.Developers')),
            ],
        ),
    ]
