# Generated by Django 2.2 on 2019-05-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologies',
            name='developers',
        ),
        migrations.AddField(
            model_name='developers',
            name='technology',
            field=models.ManyToManyField(through='employers.DevelopersTechnologies', to='employers.Technologies'),
        ),
    ]
