# Generated by Django 2.2 on 2019-06-30 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_auto_20190519_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerstechnologies',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.Developers'),
        ),
        migrations.AlterField(
            model_name='developerstechnologies',
            name='technology_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.Technologies'),
        ),
    ]
